### ISSUE TITLE
about checkpoint

### ISSUE THREAD

**Issue by chongkuiqi** [jackyzengl/GRID#1]
Thanks for your work! Would any checkpoint be released ? I want to do a test now.

**Comment by Leib-Niz** [comment]
The checkpoints will be released soon.
If you want a checkpoint for test now, please send an e-mail to nz22@mails.tsinghua.edu.cn, and we would reply to your e-mail with a checkpoint for test.

**Comment by chongkuiqi** [comment]
> The checkpoints will be released soon. If you want a checkpoint for test now, please send an e-mail to [nz22@mails.tsinghua.edu.cn](mailto:nz22@mails.tsinghua.edu.cn), and we would reply to your e-mail with a checkpoint for test.

I have already sent an email, thanks
